### ISSUE TITLE
Forgot -

### ISSUE THREAD

**Issue by yejinjkim** [jyori112/pytorch-word2vec#2]
Hi, I think you forgot to add -
self.offset = np.concatenate((-np.arange(1, window+1)[::-1], np.arange(1, window+1)))

https://github.com/jyori112/pytorch-word2vec/blob/a1bce3414189753e11c192bf722ab7b9a033bd6a/data.py#L65

**Comment by jyori112** [comment]
Thank you for pointing this bug.
Fixed it in commit 584257b6d731a0858b4b1d43daf18ec6d4230317
