### ISSUE TITLE
int32 -> int64

### ISSUE THREAD

**Issue by yejinjkim** [jyori112/pytorch-word2vec#3]
Hi, I think those two int32 should be int64 to be compatible with LongTensor :)
https://github.com/jyori112/pytorch-word2vec/blob/a1bce3414189753e11c192bf722ab7b9a033bd6a/data.py#L62

https://github.com/jyori112/pytorch-word2vec/blob/a1bce3414189753e11c192bf722ab7b9a033bd6a/data.py#L83

**Comment by jyori112** [comment]
Thank you.
Fixed this in effa9dbfaa05b2c031c367371a952cf7dc2daea5
